---
title: "Stat 5443: Computational Statistics"
author: "Dr. Jyotishka Datta"
output: 
  html_document:
    number_sections: no
    theme: united
    toc: yes
    toc_depth: '2'
    toc_float: true
---
# Course Outlines


### Module 1: Foundations:

1.	Computational Complexity
2.	Introduction to R / basic programming.
3.	Introduction to Algorithms and basic concepts (e.g. sorting)
4.	Divide-and-Conquer Strategy.
5.	Linear Systems (Gaussian Elimination, Cholesky Decomposition etc.)



### Module 2: Sampling:

1.	Accept-Reject Scheme
2.	Rejection sampling and Envelope.
3.	Advanced Sampling Techniques:
   -	Monte Carlo Integration
   -	Importance Sampling, SIR, Adaptive Rejection Sampling.
4.	Markov Chain Monte Carlo.
   -	Basic Theory.
   -	Metropolis & Metropolis-Hastings.
   -	Gibbs sampler.
5.	Sampling strategies for Bayesian Inference.

### Module 3: Statistical Learning:
#### A.	Background / Introduction

1.	Unsupervised and Supervised Learning.
2.	Examples.
3.	Bias-Variance Decomposition.
4.	Accuracy vs. Model Interpretability.

#### B.	Unsupervised Learning

1.	K-nearest neighbour
2.	PCA.
3. Multidimensional Scaling
C.	Supervised Learning
1.	Modern Regression: (large p, small n: wide data)
   -	Basics - Geometry of Regression.
   -	Subset selection: forward selection/backward selection/Best subset    - AIC.
   -	Shrinkage and Selection: Ridge, LASSO, Elastic Net.
   -	Cross-validation (general)
   -	Bayesian Lasso and Horseshoe.
   -	Principal Components Regression.
2.	Classification:

   -	Logistic Regression (with ???1 penalty).
   -	LDA and QDA.
   -	Comparison.
   
3.	Decision Tree
4.	Bagging, Boosting.
5.	Application of Bootstrap (general)
6.	Random Forest.
7.	Support Vector Machines.

### Module 4: Advanced topics:

1. Artificial Neural Network.

Note: This is only a tentative list of topics - the instructor may add topics or change the length of time spent on any particular topic to accommodate this particular class of students. 

# R Demos and in-class examples

All the R examples shown in class for Stat 5443 (Computational Statistics) are given below as a list. 
Some of the codes are my own and the rest are either derived or taken from the R codes are taken from various resources such as matrix examples in R tutorial by Prof. Giovanni Petris, MCMC examples by Prof. David Draper and the [R codes](http://www-bcf.usc.edu/~gareth/ISL/code.html) accompanying the [ISLR book](http://www-bcf.usc.edu/~gareth/ISL/index.html). 



The book website also has a link to the MOOC for Statistical Learning by Prof.s Hastie and Tibshriani which has a large interesection with the second half of the class : starting from modern regression to random forest. It's a great lecture series. 

0. [Why R?](http://dattahub.github.io/stat5443/why_R.html)
1. [Matrix Example in R](http://dattahub.github.io/stat5443/matrix_R.html)
2. [Efficiency Considerations](http://dattahub.github.io/stat5443/intro_R_adv.html)
3. [Random Variable Generation](http://dattahub.github.io/stat5443/rvgen.html)
4. [Lab Example 1: Quantile Transform](http://dattahub.github.io/stat5443/lab_ex_sampling_2020_solutions.html) 
5. [Lab Example 2: Quantile Transform](http://dattahub.github.io/stat5443/lab_exercise_sampling_2.html)
6. [Importance Sampling](http://dattahub.github.io/stat5443/importance_sampling_demo.html)
7. [Independent MH examples](http://dattahub.github.io/stat5443/indep_mh_examples.html)
8. [Gibbs Sampling Finite Mixture](http://dattahub.github.io/stat5443/gibbs-example-finite-mixture.html)
9. [Gibbs Sampling Demo](http://dattahub.github.io/stat5443/gibbs.html)
10. [PCA](http://dattahub.github.io/stat5443/demoPCA.html)
11. [Modern Regression 1](http://dattahub.github.io/stat5443/regression_demo_1.html)
12. [Modern Regression 2](http://dattahub.github.io/stat5443/regression_demo_2.html)
13. [Lab on Shrinkage Methods: Ridge, Lasso etc.](http://dattahub.github.io/stat5443/lab_glmnet.html) and [2019's version](http://dattahub.github.io/stat5443/lab_glmnet_2019.html)
14. [Solutions to Lab on Shrinkage Methods: Ridge, Lasso etc.](http://dattahub.github.io/stat5443/lab_glmnet_soln.html)
15. [Modern Regression 3](http://dattahub.github.io/stat5443/regression_demo_3.html)
16. [Logistic Demo](http://dattahub.github.io/stat5443/logistic_demo.html)
17. [Final Project Data](http://dattahub.github.io/stat5443/final_projectintro.html)
18. [Decision Tree, Random Forest](http://dattahub.github.io/stat5443/tree_demo.html)
19.  [Multidimensional Scaling](http://dattahub.github.io/stat5443/mds_demo.html)
20.  [Support Vector Machine](http://dattahub.github.io/stat5443/svm_islr.html)



