<!DOCTYPE html>
<html lang="en"><head>
<script src="npstats_lec0_files/libs/clipboard/clipboard.min.js"></script>
<script src="npstats_lec0_files/libs/quarto-html/tabby.min.js"></script>
<script src="npstats_lec0_files/libs/quarto-html/popper.min.js"></script>
<script src="npstats_lec0_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="npstats_lec0_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="npstats_lec0_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="npstats_lec0_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.6.42">

  <meta name="author" content="Jyotishka Datta">
  <meta name="dcterms.date" content="2026-08-24">
  <title>Nonparametric Statistics</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="npstats_lec0_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="npstats_lec0_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="npstats_lec0_files/libs/revealjs/dist/theme/quarto-2f366650f320edcfcf53d73c80250a32.css">
  <link href="npstats_lec0_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="npstats_lec0_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="npstats_lec0_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="npstats_lec0_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="npstats_lec0_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="npstats_lec0_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Nonparametric Statistics</h1>
  <p class="subtitle">Introduction: Lecture 0</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Jyotishka Datta 
</div>
        <p class="quarto-title-affiliation">
            Virginia Tech
          </p>
    </div>
</div>

  <p class="date">2026-08-24</p>
</section>
<section id="about-me" class="slide level2">
<h2>About Me</h2>
<ul>
<li>Associate Professor at VT Statistics.</li>
<li>Research area: Statistics / Machine Learning / (Applied) Probability.
<ul>
<li>Statistical methods for high-dimensional data with structures.</li>
<li>Applications: human genomics, crime forecasting, infectious disease.</li>
</ul></li>
<li>Born in Calcutta (Kolkata), India. Attended Indian Statistical Institute.</li>
<li>Mumbai, India — Barclays Bank, PLC — modelling credit card default and fraud detection.</li>
<li>Purdue University: Ph.D.&nbsp;in Statistics.</li>
<li>Postdoc at Duke University and SAMSI (Statistics and Applied Mathematical Sciences Institute).</li>
</ul>
</section>
<section>
<section id="syllabus" class="title-slide slide level1 center" data-background-color="#861F41">
<h1>Syllabus</h1>

</section>
<section id="outline-of-this-course-part-i" class="slide level2 scrollable">
<h2>Outline of This Course — Part I</h2>
<p><strong>Foundations and One/Two-Sample Methods</strong></p>
<ol type="1">
<li>Why nonparametric? Parametric vs.&nbsp;distribution-free inference; Pitman efficiency</li>
<li>Permutation tests: the unifying idea behind most of what follows</li>
<li>Bootstrap and resampling, confidence intervals, bootstrap hypothesis tests</li>
<li>Ranks and order statistics (just enough theory to understand what follows)</li>
<li>One-sample and paired-sample tests: sign test, Wilcoxon signed-rank test</li>
<li>Two-sample tests: Mann–Whitney, Wilcoxon rank-sum, and permutation-based alternatives</li>
<li>Multiple-sample methods: Kruskal–Wallis and Friedman tests</li>
</ol>
</section>
<section id="outline-of-this-course-part-ii" class="slide level2 scrollable">
<h2>Outline of This Course — Part II</h2>
<p><strong>More Advanced Topics</strong></p>
<ol type="1">
<li>Rank-based linear models — ranks inside <code>lm()</code>, Spearman and Kendall correlation</li>
<li>Goodness-of-fit tests: KS, Lilliefors, Anderson–Darling</li>
<li>Kernel Density Estimation and <span class="math inline">\(k\)</span>-nearest neighbors</li>
<li>Bootstrap in depth : bootstrap in regression, the parametric bootstrap</li>
<li>Survival Analysis: Kaplan–Meier estimator and log-rank test</li>
<li>Implement all of the above in <code>R</code>, with and without packages</li>
</ol>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>If you have taken CMDA 2006 with me, some of these will feel familiar, but the treatment will be faster and more theoretical throughout. This is only a tentative list of topics and may change to accommodate this class.</p>
</div>
</div>
</div>
</section>
<section id="how-to-reach-me" class="slide level2">
<h2>How to Reach Me</h2>
<ul>
<li><strong>Office:</strong> Hutcheson 409C</li>
<li><strong>Email:</strong> jyotishka@vt.edu<br>
(Subject line: STAT 3504 + [Your query])</li>
<li><strong>Class time:</strong> TR 2:00–3:15 pm</li>
<li><strong>Office Hours:</strong> Will be updated on Canvas</li>
<li><strong>Graduate Teaching Assistant (GTA):</strong> Jacob Gareis
<ul>
<li>Email: jacobgareis@vt.edu</li>
<li>Office Hours: Will be updated on Canvas</li>
</ul></li>
</ul>
</section>
<section id="grades" class="slide level2">
<h2>Grades</h2>
<p><strong>Grade Distribution:</strong></p>
<ul>
<li>Two statistics midterms: 25% each</li>
<li>Homework: 25%</li>
<li>In-class activities / exercises: 25%</li>
<li>Final Exam: 25%</li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th>Interval</th>
<th>Grade</th>
<th>Interval</th>
<th>Grade</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>[93, ∞)</td>
<td>A</td>
<td>[73, 77)</td>
<td>C</td>
</tr>
<tr class="even">
<td>[90, 93)</td>
<td>A−</td>
<td>[70, 73)</td>
<td>C−</td>
</tr>
<tr class="odd">
<td>[87, 90)</td>
<td>B+</td>
<td>[67, 70)</td>
<td>D+</td>
</tr>
<tr class="even">
<td>[83, 87)</td>
<td>B</td>
<td>[63, 67)</td>
<td>D</td>
</tr>
<tr class="odd">
<td>[80, 83)</td>
<td>B−</td>
<td>[60, 63)</td>
<td>D−</td>
</tr>
<tr class="even">
<td>[77, 80)</td>
<td>C+</td>
<td>[0, 60)</td>
<td>F</td>
</tr>
</tbody>
</table>
</section>
<section id="homework-rules" class="slide level2">
<h2>Homework Rules</h2>
<ul>
<li>Homework assignments will be frequent and will require using R.</li>
<li>Extensions will <strong>not</strong> be granted. Assignments accepted up to 24 hours late with a 20% penalty.</li>
<li>You may discuss assignments with others, but <strong>what you turn in must be your own work</strong>.</li>
<li>No sharing of written work or solutions.</li>
<li>We grade <strong>solutions, not answers</strong> — show your work. Answers without justification receive no credit.</li>
<li>All homework will have one week to submit unless otherwise announced.</li>
<li>The <strong>lowest homework grade</strong> will be dropped.</li>
</ul>
</section>
<section id="policy-on-use-of-generative-ai" class="slide level2 smaller">
<h2>Policy on Use of Generative AI</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Generative AI Policy</strong></p>
</div>
<div class="callout-content">
<p>You may use tools such as ChatGPT or Copilot to <strong>support learning, not replace your authorship</strong>. When I grade an assignment, I should be grading <strong>your</strong> work.</p>
<p><strong>Permitted:</strong> Brainstorm, outline, debug, revise, or generate examples that you verify and rewrite. Use AI only when the assignment allows it.</p>
<p><strong>Not permitted:</strong> Submitting AI text or code as your own; using AI on quizzes or exams unless explicitly allowed; entering confidential or restricted data.</p>
<p><strong>Disclosure:</strong> If you used AI, add a one-line “AI use” note at the end listing the tool, what you asked, and how you changed or verified the output.<br>
<em>Example:</em> “AI use: ChatGPT for an outline; I rewrote sections and checked citations.”</p>
<p><strong>Accountability:</strong> You are responsible for accuracy, originality, and citation. Work may be checked through follow-up questions or originality tools. Your voice and reasoning must remain prominent.</p>
</div>
</div>
</div>
</section>
<section id="some-references" class="slide level2 scrollable">
<h2>Some References</h2>
<ul>
<li>No required textbook. Following the lecture slides should be sufficient for tests.</li>
<li>Primary reference for concepts and homework:<br>
<strong>Nonparametric Statistical Inference, 5th ed.</strong> — Gibbons &amp; Chakraborti</li>
<li>Other references:
<ol type="1">
<li>Higgins. <em>Introduction to Modern Nonparametric Statistics.</em></li>
<li>Hollander and Wolfe. <em>Nonparametric Statistical Methods.</em></li>
<li>Sprent and Smeeton. <em>Applied Nonparametric Statistical Methods.</em></li>
<li>Conover. <em>Practical Nonparametric Statistics.</em></li>
</ol></li>
<li>You are responsible for taking notes, including from class discussions you may have missed.</li>
</ul>
</section>
<section id="software" class="slide level2 scrollable">
<h2>Software</h2>
<ul>
<li>We will use <strong>R</strong> throughout the course. Install it on your laptop (or computing resource of choice).</li>
<li>Available free from: <a href="http://cran.r-project.org/" class="uri">http://cran.r-project.org/</a></li>
<li>Recommended interface: <strong>RStudio</strong> — <a href="https://www.rstudio.com/" class="uri">https://www.rstudio.com/</a></li>
<li>Useful online resources:
<ol type="1">
<li>ATS UCLA R Page: <a href="http://statistics.ats.ucla.edu/stat/r/" class="uri">http://statistics.ats.ucla.edu/stat/r/</a></li>
<li>Quick R: <a href="http://www.statmethods.net/" class="uri">http://www.statmethods.net/</a></li>
<li>R-Bloggers: <a href="https://www.r-bloggers.com/" class="uri">https://www.r-bloggers.com/</a></li>
<li>R for Data Science: <a href="http://r4ds.had.co.nz/" class="uri">http://r4ds.had.co.nz/</a></li>
</ol></li>
</ul>
</section></section>
<section>
<section id="introduction" class="title-slide slide level1 center" data-background-color="#861F41">
<h1>Introduction</h1>

</section>
<section id="parametric-and-nonparametric-statistics" class="slide level2">
<h2>Parametric and Nonparametric Statistics</h2>
<ul>
<li><strong>Parameter:</strong> A constant (usually unspecified) that characterises a population — broadly includes any description of population characteristics.</li>
<li><strong>Statistic:</strong> A function of observations that does not depend on unknown parameters.</li>
<li><strong>Inference:</strong> Using statistics to infer something about the population — mainly estimation and hypothesis testing. What makes it <em>scientific</em> is the ability to make statements about accuracy or reliability.</li>
</ul>
<div class="fragment">
<ul>
<li>Some statistics are more popular than others, e.g.&nbsp;sample mean vs.&nbsp;median. <strong>Why?</strong></li>
</ul>
</div>
<div class="fragment">
<ul>
<li><strong>Central Limit Theorem:</strong> The sample mean from a large sample is approximately normally distributed.</li>
</ul>
</div>
</section>
<section id="central-limit-theorem" class="slide level2">
<h2>Central Limit Theorem</h2>
<ul>
<li>This is the reason we see Normal distributions everywhere!</li>
<li>The <strong>Central Limit Theorem</strong> is one of the most important results in all of mathematics.</li>
<li>The sum of <span class="math inline">\(N\)</span> independent, identically distributed random variables is approximately <strong>Normally distributed</strong>.</li>
<li>Example: if you flip a coin many times, the probability of getting a given number of heads follows a Normal curve with mean equal to half the total number of flips (De Moivre’s classic result).</li>
</ul>
<p><a href="https://jdatta.shinyapps.io/demoivre/" class="uri">https://jdatta.shinyapps.io/demoivre/</a></p>
</section>
<section id="general-clt" class="slide level2 center">
<h2>General CLT</h2>

<img data-src="art/clt-1.png" style="width:90.0%" alt="Details in slide" class="r-stretch quarto-figure-center"><p class="caption">Illustration of the Central Limit Theorem — details in slide</p></section>
<section id="section" class="slide level2 center">
<h2></h2>

<img data-src="art/cartoon16.jpg" style="width:70.0%" alt="Details in slide" class="r-stretch quarto-figure-center"><p class="caption">Statistical cartoon — details in slide</p></section></section>
<section>
<section id="parametric-versus-nonparametric" class="title-slide slide level1 center" data-background-color="#861F41">
<h1>Parametric versus Nonparametric</h1>

</section>
<section id="parametric-inference" class="slide level2">
<h2>Parametric Inference</h2>
<ul>
<li><strong>Parametric Inference:</strong> Estimation and inference based on an assumed form of the distribution.</li>
<li><strong>Example</strong> (modified from G&amp;C 4.13): Scores on a certain IQ test are assumed normally distributed, <span class="math inline">\(X_i \sim N(\mu,\, \sigma^2 = 100)\)</span>. Eighteen girls were tested with scores:<br>
114, 81, 87, 114, 113, 87, 111, 89, 93, 108, 99, 93, 100, 95, 93, 95, 106, 108.</li>
<li><strong>Question:</strong> Is the mean IQ significantly greater than 100?</li>
<li><strong>Hypotheses:</strong> <span class="math inline">\(H_0: \mu = 100\)</span>, <span class="math inline">\(H_A: \mu &gt; 100\)</span></li>
<li>We can carry out a <span class="math inline">\(z\)</span>-test based on the normality assumption.</li>
</ul>
<div class="fragment">
<ul>
<li>Conclusions are valid <strong>as long as the assumptions are valid.</strong></li>
</ul>
</div>
</section>
<section id="questions-to-ask-about-any-test" class="slide level2">
<h2>Questions to Ask About Any Test</h2>
<ul>
<li>What are the assumptions behind a particular test?</li>
</ul>
<div class="fragment">
<ul>
<li>For example, the <span class="math inline">\(z\)</span>-test assumes IID, normally distributed data and known variance.</li>
</ul>
</div>
<div class="fragment">
<ul>
<li>How do we test if those assumptions are valid?<br>
→ <strong>Goodness-of-fit tests</strong>, e.g.&nbsp;Lilliefors or Shapiro–Wilk tests for normality.</li>
</ul>
</div>
<div class="fragment">
<ul>
<li>Can we make other, weaker assumptions? (e.g.&nbsp;symmetry or independence?)</li>
</ul>
</div>
<div class="fragment">
<ul>
<li>How do we test the hypothesis <strong>without</strong> the distributional assumptions?<br>
→ <strong>Nonparametric alternatives.</strong></li>
</ul>
</div>
<div class="fragment">
<ul>
<li>You can also ask a more basic question: are the numbers really random? There are methods for that too.</li>
</ul>
</div>
</section>
<section id="one-sample-z-test" class="slide level2">
<h2>One-Sample <span class="math inline">\(Z\)</span>-Test</h2>
<ul>
<li><strong>Assumption:</strong> <span class="math inline">\(X_1, X_2, \ldots, X_n \overset{\text{iid}}{\sim} N(\mu,\, \sigma^2)\)</span>, <span class="math inline">\(\mu\)</span> unknown, <span class="math inline">\(\sigma^2\)</span> known.</li>
<li><strong>Null hypothesis:</strong> <span class="math inline">\(H_0: \mu = \mu_0\)</span></li>
<li><strong>Test statistic:</strong></li>
</ul>
<p><span class="math display">\[Z = \frac{\bar{X} - \mu_0}{\sigma / \sqrt{n}}\]</span></p>
<p>Under <span class="math inline">\(H_0\)</span>, <span class="math inline">\(Z \sim N(0, 1)\)</span>.</p>
<ul>
<li>If the observed <span class="math inline">\(Z\)</span> is “too large,” it is unlikely to have come from <span class="math inline">\(N(0,1)\)</span>.</li>
<li>We control how large is “too large” by fixing the <strong>Type I error</strong>:</li>
</ul>
<p><span class="math display">\[\text{Type I error} = P(\text{Reject } H_0 \mid H_0 \text{ true}) \leq \alpha\]</span></p>
</section>
<section id="z-test-continued" class="slide level2">
<h2>Z-Test, Continued</h2>
<p><span class="math display">\[Z = \frac{\bar{X} - \mu_0}{\sigma / \sqrt{n}}\]</span></p>
<ul>
<li><p>P-values are exact as long as <span class="math inline">\(\bar{X}\)</span> is normally distributed — guaranteed when <span class="math inline">\(X_i \sim N(\mu, \sigma^2)\)</span>, giving <span class="math inline">\(\bar{X} \sim N(\mu,\, \sigma^2/n)\)</span>.</p></li>
<li><p>But this is a strong assumption! What if <span class="math inline">\(X_i\)</span>’s are bounded, discrete, or skewed?</p></li>
</ul>
<div class="fragment">
<ul>
<li><p><strong>The answer is “yes, you can still apply these tests” — if your sample size is large.</strong></p></li>
<li><p>You don’t need individual <span class="math inline">\(X_i\)</span>’s to be normal, as long as <span class="math inline">\(\bar{X}\)</span> is <strong>approximately</strong> normal.</p></li>
<li><p>This is what the CLT guarantees — but you need a large enough sample, and the CLT conditions must hold.</p></li>
</ul>
</div>
</section>
<section id="tests-based-on-normality" class="slide level2">
<h2>Tests Based on Normality</h2>
<p>There is nothing exceptional about the <span class="math inline">\(z\)</span>-test.</p>
<ul>
<li>If <span class="math inline">\(\sigma^2\)</span> is unknown and estimated by <span class="math inline">\(S^2\)</span> → <strong><span class="math inline">\(t\)</span>-test</strong></li>
<li>Single sample → <strong>paired <span class="math inline">\(t\)</span>-test</strong> → <strong>two-sample <span class="math inline">\(t\)</span>-test</strong> → <strong>ANOVA (<span class="math inline">\(K\)</span> samples)</strong></li>
</ul>
<p>All of these are parametric tests that are:</p>
<ul>
<li><strong>Exact</strong> under normality</li>
<li><strong>Approximately correct</strong> for large samples (by CLT)</li>
</ul>
<p>So one good reason to look for alternative methods is <strong>small sample size</strong>.</p>
</section>
<section id="sample-size-requirements-for-parametric-tests-with-non-normal-data" class="slide level2 smaller">
<h2>Sample Size Requirements for Parametric Tests with Non-Normal Data</h2>
<p>Parametric tests can still be used with non-normal data, given sufficient sample size:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Parametric Analysis</th>
<th>Sample Size Required (Non-Normal Data)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1-sample <span class="math inline">\(t\)</span>-test</td>
<td><span class="math inline">\(n &gt; 20\)</span></td>
</tr>
<tr class="even">
<td>2-sample <span class="math inline">\(t\)</span>-test</td>
<td>Each group: <span class="math inline">\(n \geq 15\)</span></td>
</tr>
<tr class="odd">
<td>One-Way ANOVA (2–9 groups)</td>
<td>Each group: <span class="math inline">\(n \geq 15\)</span></td>
</tr>
<tr class="even">
<td>One-Way ANOVA (10–12 groups)</td>
<td>Each group: <span class="math inline">\(n \geq 20\)</span></td>
</tr>
</tbody>
</table>
<p>But small sample size is <strong>not the only</strong> reason to switch to nonparametric methods.</p>
</section>
<section id="non-parametric-methods" class="slide level2">
<h2>Non-Parametric Methods</h2>
<ul>
<li>The main attraction: <strong>fewer assumptions</strong> about the underlying distribution.</li>
<li><strong>Advantage:</strong> Robustness — inference remains valid under model misspecification.</li>
</ul>
<div class="fragment">
<ul>
<li><strong>Price to pay:</strong> If distributional assumptions are true, parametric methods often have more <strong>power</strong>.
<ul>
<li>If data truly come from <span class="math inline">\(N(\mu, \sigma^2)\)</span> and you use a test based on that, you have a higher chance of correctly detecting the alternative.</li>
</ul></li>
</ul>
</div>
<div class="fragment">
<ul>
<li>On the other hand, if assumptions are <em>wrong</em> (e.g.&nbsp;data follow a Cauchy but you assume Normal), nonparametric methods can be <em>infinitely more</em> powerful.</li>
</ul>
</div>
<div class="fragment">
<blockquote>
<p>“The basic idea of nonparametric inference is to use data to infer an unknown quantity while making as few assumptions as possible.”</p>
</blockquote>
</div>
</section>
<section id="distribution-free" class="slide level2">
<h2>Distribution-Free?</h2>
<ul>
<li>“Nonparametric” is actually a <strong>misnomer</strong>. A more accurate term: <strong>Distribution-Free Statistics</strong>.</li>
<li>Some prefer the term <strong>infinite-dimensional inference</strong>.</li>
<li>We will still estimate and test hypotheses about parameters — but the <strong>form of the distribution is not assumed</strong>.</li>
</ul>
<div class="fragment">
<ul>
<li>Often we only assume that random variables are <strong>independent and identically distributed (IID)</strong>.</li>
</ul>
</div>
<div class="fragment">
<ul>
<li>Test and estimation procedures require <strong>relatively fewer assumptions</strong> about the population distribution.</li>
</ul>
</div>
</section></section>
<section>
<section id="history-of-nonparametric-statistics" class="title-slide slide level1 center" data-background-color="#861F41">
<h1>History of Nonparametric Statistics</h1>

</section>
<section id="the-first-nonparametric-test" class="slide level2">
<h2>The First Nonparametric Test</h2>
<p>These anecdotes are mainly from Sprent &amp; Smeeton’s book and <em>The Lady Tasting Tea</em> by David Salsburg.</p>
<p>The first chapter of the Book of Daniel records that on the orders of Nebuchadnezzar certain favoured children were to be specially fed on the king’s meat and wine for 3 years. Reluctant to defile himself with such luxuries, Daniel pleaded that he and three of his brethren be fed instead on pulse for 10 days. After that time the four were declared ‘fairer and fatter in flesh than all of the children which did eat the portion of the king’s meat’. This evidence was taken on commonsense grounds to prove the superiority of a diet of pulse.</p>
<p>Although the biblical analysis is informal, it contains the seed of a nonparametric test.</p>
</section>
<section id="early-history" class="slide level2">
<h2>Early History</h2>
<p><strong>John Arbuthnot (1710)</strong> observed that in each year from 1629 to 1710, the number of males christened in London exceeded the number of females. He used this to test whether the birth ratio was 1:1. (<strong>Binomial test?</strong>)</p>
<p>Data: <a href="https://www.openintro.org/data/index.php?data=arbuthnot" class="uri">https://www.openintro.org/data/index.php?data=arbuthnot</a></p>
<p><strong>Francis Galton (1892)</strong> developed a measure — which he called a “centissimal scale” — to assess agreement between patterns (categorical data) on corresponding fingertips on left and right hands.</p>
<p><strong>Karl Pearson (1900)</strong> proposed the well-known <strong>chi-squared goodness-of-fit test</strong> for any discrete distribution.</p>
<p><strong>C. Spearman (1904)</strong> defined the <strong>rank correlation coefficient</strong> that bears his name.</p>
</section>
<section id="wilcoxon-and-mannwhitney" class="slide level2">
<h2>Wilcoxon and Mann–Whitney</h2>
<ul>
<li><strong>Frank Wilcoxon</strong>, working at American Cyanamide in the 1940s, was frustrated by the sensitivity of <span class="math inline">\(t\)</span>-tests and ANOVA to outliers.</li>
<li>He developed a nonparametric test that did not rely on distribution parameters, published in <strong>Biometrics (1945)</strong>.</li>
<li>He reportedly submitted the paper hoping it would be rejected so referees could point out his mistakes — but it was accepted, because no such methods had existed before.</li>
</ul>
<div class="fragment">
<ul>
<li>Unbeknownst to Wilcoxon, economists Henry B. <strong>Mann</strong> and graduate student D. Ransom <strong>Whitney</strong> were working on similar problems.</li>
<li>They published in <strong>1947</strong>, establishing a connection to Wilcoxon’s work.</li>
<li>You will learn these as the <strong>Wilcoxon rank-sum test</strong> and <strong>Mann–Whitney U test</strong>.</li>
</ul>
</div>
</section>
<section id="kolmogorov-and-smirnov" class="slide level2">
<h2>Kolmogorov and Smirnov</h2>
<ul>
<li>In the <strong>1930s</strong>, Andrei <strong>Kolmogorov</strong> and his student <strong>Smirnov</strong> developed a different test for comparing two distributions — without using any parameters.</li>
<li>This is the <strong>KS test</strong>, which you will study in detail.</li>
</ul>
<p>Both tests allowed analysis <strong>without estimating distribution parameters</strong>, marking a shift in statistical methodology from Pearson’s era.</p>
</section>
<section id="pitman-efficiency-and-are" class="slide level2">
<h2>Pitman Efficiency and ARE</h2>
<ul>
<li><p>After Wilcoxon, Mann, and Whitney, some questions remained:</p>
<ul>
<li>If data truly follow a known parametric distribution (like Normal), how bad is it to ignore normality and use nonparametric tests instead?</li>
</ul></li>
<li><p><strong>Pitman (1948)</strong> addressed this, demonstrating that nonparametric tests perform better with <strong>slight deviations</strong> from parametric models, and suggested a preference for nonparametric tests in hypothesis testing.</p></li>
<li><p>We will study <strong>Pitman Efficiency</strong> and <strong>Asymptotic Relative Efficiency (ARE)</strong>.</p></li>
</ul>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>The large-sample efficiency of the Wilcoxon test compared to the <span class="math inline">\(t\)</span>-test is <span class="math inline">\(\dfrac{3}{\pi} \approx 0.955\)</span>.</p>
</div>
</div>
</div>
</section>
<section id="further-developments" class="slide level2">
<h2>Further Developments</h2>
<ul>
<li>The field grew in the <strong>1960s</strong> with researchers exploring various nonparametric tests.</li>
<li><strong>Jaroslav Hájek</strong> published a unifying textbook in <strong>1971</strong>, linking nonparametric tests to central limit theorem conditions. Much of the theory of linear rank tests is due to Hájek.</li>
</ul>
<p><strong>This course covers everything up to this point.</strong></p>
</section>
<section id="challenges-the-bahadursavage-result" class="slide level2">
<h2>Challenges: The Bahadur–Savage Result</h2>
<ul>
<li>The first major challenge to nonparametric methodology came from <strong>Raj Bahadur</strong> at the University of Chicago.</li>
<li><strong>R.R. Bahadur and L.J. Jimmie Savage (1956)</strong> identified issues with outliers affecting nonparametric test reliability.</li>
</ul>
<blockquote>
<p>“If outliers are <strong>rare and completely wrong observations</strong>, then nonparametric methods <strong>reduce their influence</strong> on the analysis. If outliers are <strong>part of a systemic contamination</strong> of the data, then shifting to nonparametric will <strong>make matters worse</strong>.”</p>
</blockquote>
<p>I will describe the Bahadur–Savage result because it is striking and beautiful — but the mathematical tools needed to prove it are beyond the scope of this course.</p>
</section>
<section id="survival-analysis" class="slide level2">
<h2>Survival Analysis</h2>
<ul>
<li>Another widely used nonparametric method: <strong>Kaplan–Meier survival analysis</strong>.</li>
<li><strong>Survival Analysis:</strong> A set of methods for analysing data where the outcome variable is the <strong>time until the occurrence of an event of interest</strong>.
<ul>
<li>Events: death, disease occurrence, equipment failure, marriage, etc.</li>
<li>Literally anything where we ask: <em>How long does it take to…?</em></li>
</ul></li>
</ul>
<div class="fragment">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="art/KM_cite.jpg" alt="Details in slide" height="180"></p>
<figcaption>Kaplan-Meier citation count — details in slide</figcaption>
</figure>
</div>
</div>
<div class="fragment">
<p>…and it’s a <strong>nonparametric method!</strong></p>
</div>
</section>
<section id="survival-analysis-continued" class="slide level2 smaller">
<h2>Survival Analysis, Continued</h2>
<p>What’s the second most cited article?</p>
<div class="columns">
<div class="column" style="width:50%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="art/top100_cited.jpg" style="width:90.0%" alt="Details in slide"></p>
<figcaption>Top 100 most cited papers — details in slide</figcaption>
</figure>
</div>
</div><div class="column" style="width:50%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="art/Stiegler.jpg" style="width:90.0%" alt="Details in slide"></p>
<figcaption>Cox’s proportional hazard paper — details in slide</figcaption>
</figure>
</div>
</div></div>
<ul>
<li>Later in the course, we will learn the <strong>Bootstrap</strong>.</li>
<li>At least 10 papers in this list use Bootstrap or a version of it applied to biological data.</li>
<li>The most well-known: <em>Confidence limits on phylogenies: an approach using the bootstrap</em>, Felsenstein (1985). Cited by 37,710.</li>
</ul>
</section></section>
<section>
<section id="parametric-vs.-nonparametric-details" class="title-slide slide level1 center" data-background-color="#861F41">
<h1>Parametric vs.&nbsp;Nonparametric — Details</h1>

</section>
<section id="parametric-inference-iq-example" class="slide level2">
<h2>Parametric Inference — IQ Example</h2>
<p><strong>Example:</strong> Scores on a certain IQ test are normally distributed with <span class="math inline">\(\sigma^2 = 100\)</span>. Eighteen girls of similar age had scores:</p>
<p><span class="math display">\[114,\ 81,\ 87,\ 114,\ 113,\ 87,\ 111,\ 89,\ 93,\ 108,\ 99,\ 93,\ 100,\ 95,\ 93,\ 95,\ 106,\ 108\]</span></p>
<p><strong>Question:</strong> Is the mean IQ significantly greater than 100?</p>
<p><strong><span class="math inline">\(H_0\)</span>:</strong> <span class="math inline">\(\mu = 100\)</span> <span class="math inline">\(\quad\)</span> <strong><span class="math inline">\(H_A\)</span>:</strong> <span class="math inline">\(\mu &gt; 100\)</span></p>
<p>→ Carry out a <span class="math inline">\(z\)</span>-test based on the normality assumption.</p>
<p>Conclusions are valid <strong>as long as the assumptions are valid.</strong></p>
</section>
<section id="iq-example-nonparametric-version" class="slide level2">
<h2>IQ Example — Nonparametric Version</h2>
<ul>
<li>The IQ scores of 18 girls were:<br>
114, 81, 87, 114, 113, 87, 111, 89, 93, 108, 99, 93, 100, 95, 93, 95, 106, 108.</li>
<li><strong>We do not assume the scores are Normal, but we do assume the scores are IID.</strong></li>
</ul>
<div class="fragment">
<ul>
<li><strong>Changed Question:</strong> Is the <del>mean</del> <strong>median</strong> IQ significantly greater than 100?</li>
</ul>
</div>
<div class="fragment">
<ul>
<li>We can use <strong>one-sample nonparametric tests</strong> (first module of this course).</li>
</ul>
</div>
</section>
<section id="why-study-nonparametric-statistics" class="slide level2">
<h2>Why Study Nonparametric Statistics?</h2>
<ul>
<li>In many applications, there is <strong>no prior knowledge</strong> of the underlying distribution.</li>
<li>If parametric assumptions are violated, parametric test procedures can give <strong>misleading or wrong results</strong>.</li>
<li>For studies with <strong>small sample sizes (<span class="math inline">\(n \leq 30\)</span>)</strong>, Normal approximations do not work well.</li>
</ul>
<div class="fragment">
<ul>
<li>Therefore, we need methods that require <strong>very little model/distributional assumptions</strong>,</li>
</ul>
</div>
<div class="fragment">
<ul>
<li>or methods that are <strong>robust/insensitive</strong> to model/distributional assumptions,</li>
</ul>
</div>
<div class="fragment">
<ul>
<li>and that are <strong>insensitive to outliers</strong>.</li>
</ul>
</div>
<div class="fragment">
<blockquote>
<p><strong>Nonparametric Statistics offers a solution to all of these problems!</strong></p>
</blockquote>
</div>
</section></section>
<section>
<section id="when-to-use-nonparametric-methods" class="title-slide slide level1 center" data-background-color="#861F41">
<h1>When to Use Nonparametric Methods?</h1>

</section>
<section id="simplest-method-the-sign-test" class="slide level2 scrollable">
<h2>Simplest Method: The Sign Test</h2>
<ul>
<li>With correct assumptions (e.g.&nbsp;normality), parametric methods are more efficient — but often not by as much as you’d think.<sup>1</sup></li>
<li>Many nonparametric methods convert raw values to <strong>ranks</strong> and analyse those — which can be “wasteful” if a valid parametric alternative exists.</li>
</ul>
<p><strong>The simplest nonparametric test: Sign test</strong></p>
<p>For the IQ scores of 18 girls (median = 100), roughly half of them should lie above 100 and half below — if the true median is 100.</p>
<ul>
<li>Let <span class="math inline">\(K_{100}\)</span> = number of observations <strong>above</strong> 100.</li>
<li><strong>If <span class="math inline">\(K_{100}\)</span> is too high or too low, the median is away from 100.</strong></li>
</ul>
<aside><ol class="aside-footnotes"><li id="fn1"><p>The large-sample efficiency of the Wilcoxon test vs.&nbsp;<span class="math inline">\(t\)</span>-test is <span class="math inline">\(3/\pi \approx 0.955\)</span>.</p></li></ol></aside></section>
<section id="sign-test-calculation" class="slide level2 smaller">
<h2>Sign Test — Calculation</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Obs</th>
<th>114</th>
<th>81</th>
<th>87</th>
<th>114</th>
<th>113</th>
<th>87</th>
<th>111</th>
<th>89</th>
<th>93</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Diff</td>
<td>14</td>
<td>−19</td>
<td>−13</td>
<td>14</td>
<td>13</td>
<td>−13</td>
<td>11</td>
<td>−11</td>
<td>−7</td>
</tr>
<tr class="even">
<td>Sign</td>
<td>+</td>
<td>−</td>
<td>−</td>
<td>+</td>
<td>+</td>
<td>−</td>
<td>+</td>
<td>−</td>
<td>−</td>
</tr>
</tbody>
</table>
<table class="caption-top">
<thead>
<tr class="header">
<th>Obs</th>
<th>108</th>
<th>99</th>
<th>93</th>
<th>100</th>
<th>95</th>
<th>93</th>
<th>95</th>
<th>106</th>
<th>108</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Diff</td>
<td>8</td>
<td>−1</td>
<td>−7</td>
<td>0</td>
<td>−5</td>
<td>−7</td>
<td>−5</td>
<td>6</td>
<td>8</td>
</tr>
<tr class="even">
<td>Sign</td>
<td>+</td>
<td>−</td>
<td>−</td>
<td>+</td>
<td>−</td>
<td>−</td>
<td>−</td>
<td>+</td>
<td>+</td>
</tr>
</tbody>
</table>
<p><span class="math inline">\(K_{100}\)</span> = Total number of positives = <strong>7 out of 18</strong>.</p>
<div class="fragment">
<p>Does this look too high or too low?</p>
</div>
<div class="fragment">
<p>Calculate the probability of observing 7 or fewer heads in 18 tosses of a fair coin — or just use R:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href=""></a><span class="fu">binom.test</span>(<span class="dv">7</span>, <span class="dv">18</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="sign-test-r-output" class="slide level2">
<h2>Sign Test — R Output</h2>
<pre><code>binom.test(7, 18)

    Exact binomial test

data:  7 and 18
number of successes = 7, number of trials = 18, p-value = 0.4807
alternative hypothesis: true probability of success is not equal to 0.5
95 percent confidence interval: 0.1729859 0.6425488
sample estimates:
probability of success
             0.3888889</code></pre>
<ul>
<li>P-value = <span class="math inline">\(P(\text{successes} \leq 7 \mid H_0\text{: Median IQ} = 100) = 0.4807\)</span></li>
<li>We <strong>fail to reject <span class="math inline">\(H_0\)</span></strong>: not enough evidence of a difference.</li>
<li>The sign test is intuitive enough that anyone can understand the idea — we will revisit it in more detail.</li>
</ul>
</section>
<section id="parametric-inference-arbuthnot-example" class="slide level2">
<h2>Parametric Inference (Arbuthnot Example)</h2>
<p><strong>Example:</strong> John Arbuthnot (1710) recorded the number of male and female christenings in London for each year from 1629 to 1710. The data are available at: <a href="https://www.openintro.org/data/index.php?data=arbuthnot" class="uri">https://www.openintro.org/data/index.php?data=arbuthnot</a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href=""></a>arbuthnot <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://www.openintro.org/data/csv/arbuthnot.csv"</span>)</span>
<span id="cb3-2"><a href=""></a><span class="fu">head</span>(arbuthnot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  year boys girls
1 1629 5218  4683
2 1630 4858  4457
3 1631 4422  4102
4 1632 4994  4590
5 1633 5158  4839
6 1634 5035  4820</code></pre>
</div>
</div>
<p><strong>Question:</strong> Is the proportion of male christenings significantly greater than 0.5?</p>
<p><strong>Hypotheses:</strong> <span class="math inline">\(H_0: p = 0.5\)</span> <span class="math inline">\(\quad\)</span> <span class="math inline">\(H_A: p &gt; 0.5\)</span></p>
<p>→ Carry out a one-sample <span class="math inline">\(z\)</span>-test for a proportion based on the normality assumption (CLT for large <span class="math inline">\(n\)</span>).</p>
<p>Conclusions are valid <strong>as long as the assumptions are valid.</strong></p>
</section>
<section id="arbuthnot" class="slide level2">
<h2>Arbuthnot</h2>
<ul>
<li>In each year from 1629 to 1710, the number of male christenings <strong>exceeded</strong> the number of female christenings.</li>
<li><strong>We do not assume any particular distribution, but we do assume the yearly counts are IID.</strong></li>
</ul>
<div class="fragment">
<ul>
<li><strong>Changed Question:</strong> Is the probability that males outnumber females in a given year significantly greater than 0.5?</li>
</ul>
</div>
<div class="fragment">
<ul>
<li>Let <span class="math inline">\(K\)</span> = number of years in which male christenings exceeded female christenings. Under <span class="math inline">\(H_0: p = 0.5\)</span>, we expect <span class="math inline">\(K \approx 41\)</span> out of 82 years.</li>
</ul>
</div>
</section>
<section id="sign-test" class="slide level2">
<h2>Sign test</h2>
<ul>
<li>We can use a <strong>sign test</strong> — or equivalently, an exact binomial test:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href=""></a>arbuthnot <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://www.openintro.org/data/csv/arbuthnot.csv"</span>)</span>
<span id="cb5-2"><a href=""></a>K <span class="ot">&lt;-</span> <span class="fu">sum</span>(arbuthnot<span class="sc">$</span>boys <span class="sc">&gt;</span> arbuthnot<span class="sc">$</span>girls)</span>
<span id="cb5-3"><a href=""></a><span class="fu">binom.test</span>(K, <span class="fu">nrow</span>(arbuthnot), <span class="at">alternative =</span> <span class="st">"greater"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Exact binomial test

data:  K and nrow(arbuthnot)
number of successes = 82, number of trials = 82, p-value &lt; 2.2e-16
alternative hypothesis: true probability of success is greater than 0.5
95 percent confidence interval:
 0.964126 1.000000
sample estimates:
probability of success 
                     1 </code></pre>
</div>
</div>
</section>
<section id="sign-test-drawback" class="slide level2">
<h2>Sign Test — Drawback</h2>
<div class="r-fit-text">
<p><strong>Question:</strong> Can you name one drawback of the Sign Test?</p>
</div>
<div class="fragment">
<div class="r-fit-text">
<p><strong>Answer:</strong> It completely ignores the <strong>actual magnitudes</strong> — low power (inefficient)!</p>
</div>
</div>
</section>
<section id="parametric-tests-and-their-nonparametric-alternatives" class="slide level2">
<h2>Parametric Tests and Their Nonparametric Alternatives</h2>
<table class="caption-top">
<colgroup>
<col style="width: 39%">
<col style="width: 60%">
</colgroup>
<thead>
<tr class="header">
<th>Parametric Test</th>
<th>Nonparametric Alternative</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1-sample <span class="math inline">\(t\)</span>-test, Paired <span class="math inline">\(t\)</span>-test</td>
<td>Sign test, Wilcoxon signed-rank test</td>
</tr>
<tr class="even">
<td>2-sample <span class="math inline">\(t\)</span>-test</td>
<td>Mann–Whitney U test, Wilcoxon rank-sum test</td>
</tr>
<tr class="odd">
<td>One-Way ANOVA</td>
<td>Kruskal–Wallis test, Mood’s median test</td>
</tr>
<tr class="even">
<td>Factorial DOE</td>
<td>Friedman test</td>
</tr>
<tr class="odd">
<td>Pearson’s correlation</td>
<td>Spearman’s rank correlation or Kendall’s <span class="math inline">\(\tau\)</span></td>
</tr>
</tbody>
</table>
</section>
<section id="other-nonparametric-methods" class="slide level2">
<h2>Other Nonparametric Methods</h2>
<ul>
<li><p>Most of these methods are very simple — in fact you can often derive them by <strong>replacing an observation with its rank</strong> (either within its own sample or a pooled sample).</p></li>
<li><p>I will show how many of these methods can be derived using ideas from <strong>linear regression</strong> — via the simple <code>lm()</code> function in R — after we have understood them as standalone methods.</p></li>
<li><p>Some popular nonparametric procedures are <strong>not alternatives</strong> but standalone tools — for example, the <strong>Bootstrap</strong>, which we will learn later.</p></li>
<li><p>There are also more advanced methods I won’t be able to cover: nonparametric regression, wavelets, nonparametric Bayes (e.g.&nbsp;Dirichlet processes).</p></li>
</ul>
</section>
<section id="reasons-to-use-nonparametric-vs.-parametric-methods" class="slide level2 scrollable">
<h2>Reasons to Use Nonparametric vs.&nbsp;Parametric Methods</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Reasons for Nonparametric</strong></p>
<ol type="1">
<li>Small sample size <em>(double-edged sword!)</em></li>
<li>Ordinal data, ranked data, or outliers you cannot remove</li>
<li>Data distribution doesn’t follow any known parametric distribution</li>
<li>Median is a better representative than mean (e.g.&nbsp;income, grade distributions)</li>
<li>Usually simpler tests, less affected by departures from ideal assumptions — but limited in power and conclusions</li>
</ol>
</div><div class="column" style="width:50%;">
<p><strong>Reasons for Parametric</strong></p>
<ol type="1">
<li>Large sample — statistic is approximately Normal (CLT)</li>
<li>Normality doesn’t hold, but other parametric tests apply, or data can be suitably transformed</li>
<li>Can draw more conclusions at the population level</li>
</ol>
</div></div>
</section>
<section id="whats-next" class="slide level2">
<h2>What’s Next</h2>
<div class="fragment">
<p>Please also fill out the <strong>survey about your R background</strong> on Canvas.</p>
</div>
</section>
<section class="slide level2">


</section></section>

    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>STAT 3504 — Virginia Tech | Jyotishka Datta</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="npstats_lec0_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="npstats_lec0_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="npstats_lec0_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="npstats_lec0_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="npstats_lec0_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="npstats_lec0_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="npstats_lec0_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="npstats_lec0_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="npstats_lec0_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="npstats_lec0_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="npstats_lec0_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': true,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'fade',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
    window.document.addEventListener("DOMContentLoaded", function (event) {
      const toggleBodyColorMode = (bsSheetEl) => {
        const mode = bsSheetEl.getAttribute("data-mode");
        const bodyEl = window.document.querySelector("body");
        if (mode === "dark") {
          bodyEl.classList.add("quarto-dark");
          bodyEl.classList.remove("quarto-light");
        } else {
          bodyEl.classList.add("quarto-light");
          bodyEl.classList.remove("quarto-dark");
        }
      }
      const toggleBodyColorPrimary = () => {
        const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
        if (bsSheetEl) {
          toggleBodyColorMode(bsSheetEl);
        }
      }
      toggleBodyColorPrimary();  
      const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
      tabsets.forEach(function(tabset) {
        const tabby = new Tabby('#' + tabset.id);
      });
      const isCodeAnnotation = (el) => {
        for (const clz of el.classList) {
          if (clz.startsWith('code-annotation-')) {                     
            return true;
          }
        }
        return false;
      }
      const onCopySuccess = function(e) {
        // button target
        const button = e.trigger;
        // don't keep focus
        button.blur();
        // flash "checked"
        button.classList.add('code-copy-button-checked');
        var currentTitle = button.getAttribute("title");
        button.setAttribute("title", "Copied!");
        let tooltip;
        if (window.bootstrap) {
          button.setAttribute("data-bs-toggle", "tooltip");
          button.setAttribute("data-bs-placement", "left");
          button.setAttribute("data-bs-title", "Copied!");
          tooltip = new bootstrap.Tooltip(button, 
            { trigger: "manual", 
              customClass: "code-copy-button-tooltip",
              offset: [0, -8]});
          tooltip.show();    
        }
        setTimeout(function() {
          if (tooltip) {
            tooltip.hide();
            button.removeAttribute("data-bs-title");
            button.removeAttribute("data-bs-toggle");
            button.removeAttribute("data-bs-placement");
          }
          button.setAttribute("title", currentTitle);
          button.classList.remove('code-copy-button-checked');
        }, 1000);
        // clear code selection
        e.clearSelection();
      }
      const getTextToCopy = function(trigger) {
          const codeEl = trigger.previousElementSibling.cloneNode(true);
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
      }
      const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
        text: getTextToCopy
      });
      clipboard.on('success', onCopySuccess);
      if (window.document.getElementById('quarto-embedded-source-code-modal')) {
        const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
          text: getTextToCopy,
          container: window.document.getElementById('quarto-embedded-source-code-modal')
        });
        clipboardModal.on('success', onCopySuccess);
      }
        var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
        var mailtoRegex = new RegExp(/^mailto:/);
          var filterRegex = new RegExp('/' + window.location.host + '/');
        var isInternal = (href) => {
            return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
        }
        // Inspect non-navigation links and adorn them if external
     	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
        for (var i=0; i<links.length; i++) {
          const link = links[i];
          if (!isInternal(link.href)) {
            // undo the damage that might have been done by quarto-nav.js in the case of
            // links that we want to consider external
            if (link.dataset.originalHref !== undefined) {
              link.href = link.dataset.originalHref;
            }
          }
        }
      function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
        const config = {
          allowHTML: true,
          maxWidth: 500,
          delay: 100,
          arrow: false,
          appendTo: function(el) {
              return el.closest('section.slide') || el.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'light-border',
          placement: 'bottom-start',
        };
        if (contentFn) {
          config.content = contentFn;
        }
        if (onTriggerFn) {
          config.onTrigger = onTriggerFn;
        }
        if (onUntriggerFn) {
          config.onUntrigger = onUntriggerFn;
        }
          config['offset'] = [0,0];
          config['maxWidth'] = 700;
        window.tippy(el, config); 
      }
      const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
      for (var i=0; i<noterefs.length; i++) {
        const ref = noterefs[i];
        tippyHover(ref, function() {
          // use id or data attribute instead here
          let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
          try { href = new URL(href).hash; } catch {}
          const id = href.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note) {
            return note.innerHTML;
          } else {
            return "";
          }
        });
      }
      const findCites = (el) => {
        const parentEl = el.parentElement;
        if (parentEl) {
          const cites = parentEl.dataset.cites;
          if (cites) {
            return {
              el,
              cites: cites.split(' ')
            };
          } else {
            return findCites(el.parentElement)
          }
        } else {
          return undefined;
        }
      };
      var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
      for (var i=0; i<bibliorefs.length; i++) {
        const ref = bibliorefs[i];
        const citeInfo = findCites(ref);
        if (citeInfo) {
          tippyHover(citeInfo.el, function() {
            var popup = window.document.createElement('div');
            citeInfo.cites.forEach(function(cite) {
              var citeDiv = window.document.createElement('div');
              citeDiv.classList.add('hanging-indent');
              citeDiv.classList.add('csl-entry');
              var biblioDiv = window.document.getElementById('ref-' + cite);
              if (biblioDiv) {
                citeDiv.innerHTML = biblioDiv.innerHTML;
              }
              popup.appendChild(citeDiv);
            });
            return popup.innerHTML;
          });
        }
      }
    });
    </script>
    

</body></html>